fix: escape non-boilr expressions

diff --git a/package/template/.github/workflows/main.yml b/package/template/.github/workflows/main.yml
--- a/package/template/.github/workflows/main.yml
+++ b/package/template/.github/workflows/main.yml
@@ -1,6 +1,9 @@
 # Version 0.6.0
 name: UPM Deployment
 
+env:
+  PACKAGE_ROOT: {{`{{secrets.PACKAGE_ROOT}}`}}
+
 on:
   push:
     branches: [ master ]
@@ -24,14 +27,14 @@ jobs:
 
       - name: Initialize Pipeline Variables
         run: |
-          version=$(goo package get-version "${{ secrets.PACKAGE_ROOT }}")
+          version=$(goo package get-version "$PACKAGE_ROOT")
           echo "VERSION=$version" >> $GITHUB_ENV
 
       - name: Preprocess Package
         run: |
           if [ -e "preamble.txt" ]
           then
-            find "${{ secrets.PACKAGE_ROOT }}" \( -iname "*.cs" -o -iname "*.shader" \) | while read fname; do
+            find "$PACKAGE_ROOT" \( -iname "*.cs" -o -iname "*.shader" \) | while read fname; do
               cat "preamble.txt" | goo transform inject "${fname}"
             done
           fi
@@ -40,8 +43,8 @@ jobs:
           function transfer () {
             if [ -e "$1" ]
             then
-              cp -n "$1" "${{ secrets.PACKAGE_ROOT }}"
-              touch "${{ secrets.PACKAGE_ROOT }}/$1.meta"
+              cp -n "$1" "$PACKAGE_ROOT"
+              touch "$PACKAGE_ROOT/$1.meta"
             fi
           }
           transfer README.md
@@ -49,7 +52,7 @@ jobs:
           transfer CHANGELOG.md
       - name: Prepare Package
         run: |
-          cd "${{ secrets.PACKAGE_ROOT }}"
+          cd "$PACKAGE_ROOT"
           if [ -e "Samples" ]
           then
             goo transform hide-folder "Samples"
@@ -62,20 +65,20 @@ jobs:
 
       - name: Publish UPM (scoped registry)
         run: |
-          npm publish "${{ secrets.PACKAGE_ROOT }}" --registry "https://npm.pkg.github.com/@AndtechGames"
+          npm publish "$PACKAGE_ROOT" --registry "https://npm.pkg.github.com/@AndtechGames"
         env:
-          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          NODE_AUTH_TOKEN: ${{`{{secrets.GITHUB_TOKEN}}`}}
       - name: Publish UPM (git repository)
         uses: s0/git-publish-subdir-action@develop
         env:
           REPO: self
           BRANCH: upm
-          FOLDER: "\"${{ secrets.PACKAGE_ROOT }}\""
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          MESSAGE: "Deploy: {sha} (v${{env.VERSION}})"
+          FOLDER: "\"$PACKAGE_ROOT\""
+          GITHUB_TOKEN: ${{`{{secrets.GITHUB_TOKEN}}`}}
+          MESSAGE: "Deploy: {sha} (v${{`{{env.VERSION}}`}})"
       - name: Tag Release
         run: |
           git fetch origin upm
           git checkout -f upm
-          git tag v${{env.VERSION}} HEAD
-          git push --tags || echo "::warning ::Tag failed. Has version ${{env.VERSION}} already been published?"
+          git tag v${{`{{env.VERSION}}`}} HEAD
+          git push --tags || echo "::warning ::Tag failed. Has version ${{`{{env.VERSION}}`}} already been published?"
